In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
#NumPy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1,2.0,3.3],[4,5,6.5]])
a3 = np.array([[[1,2,3],
             [4,5,6],
             [7,8,9]],
             [[10,11,12],
             [13,14,15],
             [16,17,18]]])

In [6]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
a1.shape

(3,)

In [10]:
a2.shape

(2, 3)

In [11]:
a3.shape

(2, 3, 3)

In [12]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [13]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [14]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [15]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [18]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating Arrays

In [19]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [20]:
sample_array.dtype

dtype('int64')

In [21]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
ones.dtype

dtype('float64')

In [23]:
type(ones)

numpy.ndarray

In [25]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [27]:
random_array = np.random.randint(0,10,size=(3,5))

In [28]:
random_array

array([[3, 0, 5, 0, 7],
       [5, 4, 1, 6, 5],
       [5, 2, 4, 3, 4]])

In [29]:
random_array.size

15

In [30]:
random_array.shape

(3, 5)

In [32]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.61291248, 0.12338412, 0.77904254],
       [0.34154397, 0.94398537, 0.02069746],
       [0.94794357, 0.94494679, 0.51657043],
       [0.0746062 , 0.14400554, 0.99414232],
       [0.3000113 , 0.94171998, 0.94644346]])

In [33]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.07476129, 0.08327052, 0.36593818],
       [0.39337968, 0.6869505 , 0.55695132],
       [0.81445403, 0.699773  , 0.29126233],
       [0.15217501, 0.34712054, 0.49469161],
       [0.0541811 , 0.68593363, 0.12184948]])