In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
#NumPy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2.0,3.3],[4,5,6.5]])
a3 = np.array([[[1,2,3],
             [4,5,6],
             [7,8,9]],
             [[10,11,12],
             [13,14,15],
             [16,17,18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating Arrays

In [15]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [16]:
sample_array.dtype

dtype('int64')

In [17]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
ones.dtype

dtype('float64')

In [19]:
type(ones)

numpy.ndarray

In [20]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [22]:
random_array = np.random.randint(0,10,size=(3,5))

In [23]:
random_array

array([[2, 7, 1, 4, 6],
       [4, 5, 4, 4, 0],
       [7, 0, 5, 1, 2]])

In [24]:
random_array.size

15

In [25]:
random_array.shape

(3, 5)

In [26]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.80374417, 0.27289501, 0.97780351],
       [0.42823879, 0.67232139, 0.92890038],
       [0.57148367, 0.43498745, 0.89364907],
       [0.47968042, 0.43886143, 0.09249611],
       [0.9300846 , 0.76738848, 0.07944274]])

In [27]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.37589934, 0.36344544, 0.83568633],
       [0.82744219, 0.33519449, 0.41003844],
       [0.7544806 , 0.45642956, 0.96058628],
       [0.60952794, 0.99841453, 0.81213177],
       [0.15406025, 0.66515843, 0.32765062]])

In [28]:
# Pseudo-random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10,size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [29]:
np.random.seed(7)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

## 3. Viewing arrays and matrices

In [30]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
a1

array([1, 2, 3])

In [32]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [33]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [34]:
a1[0]

1

In [35]:
a2[0]

array([1. , 2. , 3.3])

In [36]:
a2[1]

array([4. , 5. , 6.5])

In [37]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [38]:
a4 = np.random.randint(10,size=(2,3,4,5))

In [39]:
a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [40]:
a4.shape

(2, 3, 4, 5)

In [41]:
a4.ndim

4

In [42]:
a4[1][0][0][:4]

array([3, 0, 4, 8])

In [43]:
# Get the first 4 numbers of the innermost arryas
a4[:,:,:,:4]

array([[[[3, 5, 8, 8],
         [5, 0, 0, 2],
         [9, 6, 4, 9],
         [3, 3, 8, 3]],

        [[1, 0, 0, 6],
         [7, 9, 3, 0],
         [7, 7, 0, 5],
         [3, 1, 3, 1]],

        [[4, 3, 1, 9],
         [9, 1, 2, 3],
         [2, 5, 7, 3],
         [9, 9, 3, 4]]],


       [[[3, 0, 4, 8],
         [7, 2, 7, 3],
         [6, 6, 5, 6],
         [7, 1, 5, 4]],

        [[9, 9, 0, 6],
         [6, 8, 2, 4],
         [6, 1, 5, 1],
         [9, 8, 6, 5]],

        [[7, 5, 4, 9],
         [8, 1, 5, 5],
         [3, 7, 7, 9],
         [7, 5, 9, 6]]]])

## 4. Manipulating and comparing arrays

## Arithmetic

In [45]:
a1

array([1, 2, 3])

In [46]:
ones = np.ones(3)

In [47]:
ones

array([1., 1., 1.])

In [48]:
a1+ones

array([2., 3., 4.])

In [49]:
a1-ones

array([0., 1., 2.])

In [51]:
a1*ones

array([1., 2., 3.])

In [52]:
a1

array([1, 2, 3])

In [53]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [54]:
a1*a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [55]:
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [56]:
a1/ones

array([1., 2., 3.])

In [57]:
a2/a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [58]:
a2//a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [59]:
a2**2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [61]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [62]:
np.add(a1,ones)

array([2., 3., 4.])

In [63]:
a1+ones

array([2., 3., 4.])

In [64]:
a1%2

array([1, 0, 1])

In [65]:
a1/2

array([0.5, 1. , 1.5])

In [66]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])